inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - 'vendor/bundle/**/*'
  NewCops: enable
  TargetRubyVersion: 2.4

# Be lenient with line length
Layout/LineLength:
  Max: 110

# Trailing dots
Layout/DotPosition:
  EnforcedStyle: trailing

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb' # Blocks can be any length in spec files
    - '*.gemspec' # Gem spec blocks can be any size

Naming/PredicateName:
  AllowedMethods:
    - 'has_one'
    - 'has_many'
    - 'has_xml_content'

RSpec/FilePath:
  CustomTransform:
    HappyMapper: 'happymapper'

# Use older RuboCop default
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': ()

# Configuration parameters: AutoCorrect, EnforcedStyle.
# SupportedStyles: predicate, comparison
Style/NumericPredicate:
  EnforcedStyle: comparison
